# SPDX-License-Identifier: BSD-3-Clause
# SPDX-FileCopyrightText: 2025 Erlang Ecosystem Foundation

on:
  workflow_call: {}

name: "Test"

permissions:
  contents: read

jobs:
  detectToolVersions:
    name: "Detect Tool Versions"

    runs-on: ubuntu-latest

    outputs:
      otpVersion: "${{ steps.toolVersions.outputs.OTP_VERSION }}"
      rebar3Version: "${{ steps.toolVersions.outputs.REBAR3_VERSION }}"

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: "Read .tool-versions"
        id: toolVersions
        run: |
          OTP_VERSION="$(cat .tool-versions | grep erlang | cut -d' ' -f2-)"
          echo OTP: $OTP_VERSION
          echo "OTP_VERSION=${OTP_VERSION}" >> $GITHUB_OUTPUT

          REBAR3_VERSION="$(cat .tool-versions | grep rebar | cut -d' ' -f2-)"
          echo REBAR3: $REBAR3_VERSION
          echo "REBAR3_VERSION=${REBAR3_VERSION}" >> $GITHUB_OUTPUT

  format:
    name: Check Formatting

    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true

      - uses: ./.github/actions/setup-runtime-env

      - run: rebar3 fmt --check

  ct:
    name: rebar3 CT (${{ matrix.name }})

    needs: ["detectToolVersions"]

    runs-on: ${{ matrix.runs-on }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # Lowest Supported
          - otp: "27.0"
            name: "lowest"
            runs-on: ubuntu-latest
            unstable: false
          # Latest Supported
          - otp: "${{ needs.detectToolVersions.outputs.otpVersion }}"
            name: "latest"
            runs-on: ubuntu-latest
            unstable: false
          # Test Main
          - otp: "${{ needs.detectToolVersions.outputs.otpVersion }}"
            name: "main"
            runs-on: ubuntu-latest
            unstable: true

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true

      - uses: ./.github/actions/setup-runtime-env
        with:
          otp-version: ${{ matrix.otp }}
          rebar3-version: ${{ needs.detectToolVersions.outputs.rebar3Version }}

      - name: "Install Test OS Dependencies"
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          echo "PATH=$PATH" >> "$GITHUB_ENV"
          brew tap cyclonedx/cyclonedx
          brew install cyclonedx/cyclonedx/cyclonedx-cli

      - name: "Run CT Suites"
        run: rebar3 ct --cover

      - name: "Create HTML Coverage Report"
        run: rebar3 cover

      - name: "Convert Coverage to Cobertura XML"
        run: rebar3 covertool generate

      - name: Send Coverage to Coveralls
        if: always()
        uses: coverallsapp/github-action@8d6379e14d29928660c4ba802d8e85393440b329 # v2.3.8
        with:
          file: "_build/test/covertool/rebar3_sbom.covertool.xml"
          format: cobertura
          flag-name: ct-${{ matrix.name }}
          parallel: true

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage-ct-${{ matrix.name }}
          path: "_build/test/cover/*"

  finish_coverage:
    name: Finish Coveralls Report

    needs: ["ct"]

    if: ${{ always() }}

    runs-on: ubuntu-latest

    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@8d6379e14d29928660c4ba802d8e85393440b329 # v2.3.8
      with:
        parallel-finished: true
        carryforward: "ct-lowest,ct-latest,ct-main"

  lint:
    name: "Elvis Linter"

    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true

      - uses: ./.github/actions/setup-runtime-env

      - run: rebar3 lint

  dialyzer:
    name: "Check Dialyzer"

    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true

      - uses: ./.github/actions/setup-runtime-env

      - run: rebar3 dialyzer
